kubectl delete deployment actorsapi
kubectl delete deployment apigateway
kubectl delete deployment authapi
kubectl delete deployment consulservice
kubectl delete deployment moviesapi
kubectl delete deployment rabbitmq
kubectl delete services actorsapi
kubectl delete services apigateway
kubectl delete services authapi
kubectl delete services consulservice
kubectl delete services moviesapi
kubectl delete services rabbitmq
